### ISSUE TITLE
开启时报错

### ISSUE THREAD

**Issue by FXDYJ** [Micalhl/NiuZi#1]
日志如下：
2022-12-14 09:44:39 W/NiuZi: Linked class org.slf4j.impl.StaticLoggerBinder in MC服务器查询.jar but plugin not depend on it.
2022-12-14 09:44:39 W/NiuZi: Class loading logic may change in feature.
2022-12-14 09:44:39 E/NiuZi: java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'NiuZi-1.1-SNAPSHOT.mirai.jar' @46911148 of the current class, org/slf4j/LoggerFactory, and the class loader 'MC服务器查询.jar' @798256c5 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'NiuZi-1.1-SNAPSHOT.mirai.jar' @46911148, parent loader 'global-shared' @561b7d53; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'MC服务器查询.jar' @798256c5, parent loader 'global-shared' @561b7d53)
java.lang.LinkageError: loader constraint violation: when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' the class loader 'NiuZi-1.1-SNAPSHOT.mirai.jar' @46911148 of the current class, org/slf4j/LoggerFactory, and the class loader 'MC服务器查询.jar' @798256c5 for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature (org.slf4j.LoggerFactory is in unnamed module of loader 'NiuZi-1.1-SNAPSHOT.mirai.jar' @46911148, parent loader 'global-shared' @561b7d53; org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader 'MC服务器查询.jar' @798256c5, parent loader 'global-shared' @561b7d53)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:48)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//net.realmidc.niuzi.util.HikariCP.setSqlConnectionPool(HikariCP.kt:27)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//net.realmidc.niuzi.data.sql.Dao.connect(Dao.kt:20)
        at NiuZi-1.1-SNAPSHOT.mirai.jar//net.realmidc.niuzi.PluginMain.onEnable(PluginMain.kt:40)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:175)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:336)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
是不是和其他插件不兼容啊？

**Comment by Micalhl** [comment]
我认为不是，卸载我的插件后有问题吗？

**Comment by FXDYJ** [comment]
> 我认为不是，卸载我的插件后有问题吗？

卸载之后就没有问题了

**Comment by FXDYJ** [comment]
解决办法：不用那个插件了
问个问题，作者能把所有能执行的命令都写一遍吗？
我看配置文件内好多功能都没有明确的写出指令

**Comment by FXDYJ** [comment]
还有牛子排行榜和贴贴还有分手用不了
![image](https://github.com/Micalhl/NiuZi/assets/81761850/1ed37a5f-d4c7-49f0-adc9-4edb1e408e3c)
![image](https://github.com/Micalhl/NiuZi/assets/81761850/656d385a-fee3-420e-ae5e-fa47ec5ea6d7)
![image](https://github.com/Micalhl/NiuZi/assets/81761850/22974542-f06d-4c73-a783-a2c00984688f)
控制台无输出
![image](https://github.com/Micalhl/NiuZi/assets/81761850/55ec3c57-d0a0-4c25-90af-63cf3eb41ee0)
